server:
  port: 9080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.rdf.system: DEBUG


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

spring:
  application:
    name: user-api
  datasource:
    # 使用druid数据源
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/rdf_auth?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 123
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      useGlobalDataSourceStat: true
  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

feign:
  hystrix:
    enabled: true

#安全配置
security:
  oauth2:
    resource:
      id: user-api
      #指定用户信息地址
      user-info-uri: http://localhost:9002/uaa/user
      prefer-token-info: false

swagger:
  enable: true
  title: 用户API接口
  description: 用户API接口定义文档.
  version: 1.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  base-package: com.rdf.system
  base-path: /**
  exclude-path: /ops/**, /error

mapper:
  mappers: tk.mybatis.mapper.common.Mapper

mybatis:
  type-aliases-package: com.rdf.system.*.model.**
  mapper-locations: classpath:mapper/**/*.xml

oss:
  ali:
    name: daer
    password: daer123456
    uri: http://www.liuwei-daer.com
