server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.rdf.frontend: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

spring:
  application:
    name: rdf-frontend-test
  datasource:
    # 使用druid数据源
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/rdf-dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 123
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      useGlobalDataSourceStat: true

  zipkin:
    base-url: http://localhost:8005
  sleuth:
    sampler:
      percentage: 1.0

swagger:
  enable: true

mybatis:
  type-aliases-package: com.rdf.frontend.*.model.**
  mapper-locations: classpath:mapper/**/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

rdf:
  hello: rdf config is dev